import Head from 'next/head';
// import Image from 'next/image';
import { Image } from '@chakra-ui/react'
import styles from '../styles/Home.module.css';
import { Box, Container, Text } from '@chakra-ui/react';
import {getCuratedPhotos} from "../lib/api";
import React, { useState } from 'react';

// const [photos, setPhotos] = useState(data);

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mana's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box overflow= "hidden" bg="pink.100" minH="100vh">
        <Container>
          <Text
            color="purple.800"
            fontWeight="semibold"
            mb="1rem"
            textAlign="center"
            textDecoration="underline"
            fontSize={["4xl", "4xl", "5xl", "5xl"]}
          >
            Mana's Blog
          </Text>
        </Container>
        {/* {
          photos.map((pic) => (
            <img src={pic.src.original} width="500" height="500" />
          ))
        } */}

        <Image
          borderRadius='full'
          boxSize='150px'
          src='https://media-exp1.licdn.com/dms/image/C5603AQE0HuZ0I23k3w/profile-displayphoto-shrink_800_800/0/1658447265385?e=1663804800&v=beta&t=e4-a_UB33smKeGwhEZmNgO_Vl_S8BUG-CJYLN6bKAQc'
          alt='Image'
        />
        <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      </Box>

      


      

{/* export async function getServerSideProps() {
   const data = await getCuratedPhotos();
    return {
      props: {
      data,
      },
    };
  } */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

